title = "SaveInstance Fetch"
gitRepoUrl = "https://github.com/achmdfzn/SaveInstanceFetch"
changelog = false

[docusaurus]
projectName = "SaveInstanceFetch"
title = "SaveInstance Fetch"
tagline = "Full Union, Terrain, Streaming, Mesh-Recovery & Decompile support — modded by Bolohoutoh
url = "https://realslimshady2000.github.io"
baseUrl = "/SaveInstanceFetch/"

[home]
enabled = true
includeReadme = true

[[navbar.items]]
href = "https://github.com/achmdfzn/SaveInstanceFetch"
label = "GitHub"
position = "right"
