title = "SaveInstance 420 Edition"
gitRepoUrl = "https://github.com/RealSlimShady2000/SaveInstance420Edition"
changelog = false

[docusaurus]
projectName = "SaveInstance420Edition"
title = "SaveInstance 420 Edition"
tagline = "Full Union, Terrain, Streaming, Mesh-Recovery & Decompile support — modded by Robloxscripts.com"
url = "https://realslimshady2000.github.io"
baseUrl = "/SaveInstance420Edition/"

[home]
enabled = true
includeReadme = true

[[navbar.items]]
href = "https://github.com/RealSlimShady2000/SaveInstance420Edition"
label = "GitHub"
position = "right"
